<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Tue Aug 18 2020 11:53:10 GMT+0000 (Coordinated Universal Time)). */
return array(
	'src/public/dist/rml_gutenberg.lite.js' => '11ec257a0f1c0f83ad1c6f90cad3416d',
	'src/public/dist/rml_gutenberg.pro.js' => '5d4b4eb35ddac6c3af2dd818d98026ff',
	'src/public/dist/rml_shortcode.lite.js' => '3cdf92a580d48b606c5e57fa8ea19739',
	'src/public/dist/rml_shortcode.pro.js' => '4230611ce6974576909bc9324eaad2c7',
	'src/public/dist/rml.lite.js' => 'fc59578a51f2c60ec8493d8cf6bddac4',
	'src/public/dist/rml.pro.js' => '40013b22643a9bbd154c32ec14956a6f',
	'src/public/dist/rml.css' => '87f03e57ec48641c36340e94441ea6de',
);
